# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'dolfin' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # :fabric_enabled => true  # Enable Fabric for React Native
  )

  target 'dolfinTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :fabric_enabled => true,  # Ensure Fabric is enabled
      # :ccache_enabled => true
    )

    # Fix issues related to Swift compatibility if needed
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-reanimated'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'  # Ensure Swift 5 compatibility
        end
      end
    end
  end
end
